### ISSUE TITLE
unitTest reslut error

### ISSUE THREAD

**Issue by hominlinx** [andrepuschmann/math-neon#2]
hi,
In your ReadME.md (unitTest) page,I find an error about sinf_neon

```
sinf_neon   [-3.14, 3.14]   500000  3.25e+00    2.57e+09%   2.35e+00    203125  x1.62
```

As the range of sin is [-1,1],so **3.25e+00** is error??

**Comment by andrepuschmann** [comment]
I am afraid I can't help you with this. As you already figured out, the main math-neon page is probably the best source of information for this. Good look with it!
